server:
  #端口号
  port: 8085

mybatis: 
  # mapperLocations: classpath:com/wellcom/jppt/biz/dao/mapper/*.xml
  # mapperLocations: classpath*:com/wellcom/jppt/biz/dao/**/mapper/*.xml
  #mapper-locations: classpath:mapping/*Mapping.xml 
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pagehelper:
#     helperDialect: oracle
#     reasonable: true
#     supportMethodsArguments: true
#     params: count=countSql

spring:
  aop:
    proxy-target-class: true #true为使用CGLIB代理

  datasource:
    username: dfo
    password: wellcom
    url: jdbc:oracle:thin:@192.168.191.160:1521:jxdb4g
    driver-class-name: oracle.jdbc.OracleDriver
    
 
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    ###############以上为配置druid添加的配置########################################

# mp:
#   wellcom:
#     - apptest1: id1
#       test: 1
#     - apptest1: id2
#       test: 2
#   list2: [cat,dog,pig]